### PR TITLE
Billila devel

### PR DESCRIPTION
**Pull request by drighelli**

### CODE REVIEW

**Comment by lgeistlinger** [comment]
Hi @drighelli can you make sure that your branch passes R CMD build + R CMD check without errors ? Currently `R CMD build` fails due to an issue with a malformed `Imports` section in your `DESCRIPTION` file: https://github.com/Bioconductor/ISMB.OSCA/actions/runs/5465679768/jobs/9949466635?pr=17:

```
── R CMD build ─────────────────────────────────────────────────────────────────
pdflatex not found! Not building PDF manual.
* checking for file ‘.../DESCRIPTION’ ... OK
* preparing ‘ISMB.OSCA’:
* checking DESCRIPTION meta-information ... ERROR
Malformed Depends or Suggests or Imports or Enhances field.
Offending entries:
  pheatmap
scDblFinder
Entries must be names of packages optionally followed by '<=' or '>=',
white space, and a valid version number in parentheses.
See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
```

I think you are just missing a comma after `pheatmap` ...

**Comment by drighelli** [comment]
Thanks @lgeistlinger,

it should be fixed now.

**Comment by lgeistlinger** [comment]
Thanks @drighelli. It seems we are running out of memory again:

```
--- finished re-building ‘large_data.Rmd’
--- re-building ‘multi_sample.Rmd’ using rmarkdown
Killed
Error in proc$get_built_file() : Build process failed
Calls: <Anonymous> ... build_package -> with_envvar -> force -> <Anonymous>
Execution halted
Error: Process completed with exit code 1.
```

Can you try subsampling to eg something like 1000 cells per sample as I did [here](https://github.com/Bioconductor/ISMB.OSCA/blob/444d0d515139d318bcbf8f452fa1dca7ada4183b/vignettes/cell_type_annotation.Rmd#L37)?

**Comment by drisso** [comment]
@drighelli I'm taking care of the subsampling

**Comment by drisso** [comment]
Merging as it passes all checks

**Comment by drighelli** [comment]
thanks @drisso !!

**Pull request merged**
