### PR TITLE
proportional subsampling on cells for multisample

### PR DESCRIPTION
**Pull request by drighelli**
changing the sampling of the cells for multisample due to some inconsistencies in the results

PR for checking if it builds

### CODE REVIEW

**Comment by drisso** [comment]
@drighelli the explanation in the vignette should match the code: e.g., "we subsample 70% of the cells" rather than 500 cells

**Comment by drisso** [comment]
Also, are you sure you need 70% of cells? Wouldn't 50% suffice?

**Comment by drighelli** [comment]
I'm not sure about the 50%, maybe yes!
I can try...

**Comment by drisso** [comment]
Thanks @drighelli ! 

I have made a few small changes. The only substantial one is that I removed the filter on cell types for the DA analysis so to keep in the table ExE ectoderm (the only interesting one).

As soon as the checks finish feel free to merge to devel (and please bump the version in the DESCRIPTION file).

**Pull request merged**
